### ISSUE TITLE
[DataCap Application] <NOAA><Grib2-pds>

### ISSUE THREAD

**Issue by Voshell7** [cryptoAmandaL/BDE-Allocator#18]
### Version

1

### DataCap Applicant

Voshell7

### Project ID

1

### Data Owner Name

NOAA

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.noaa.gov/climate

### Social Media Handle

Voshell

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

612TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1o2qncopywo7wfgv4yqp2jaxdmxds52bir2dxjci

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a web3 community builders in Singapore, learning and sharing web3 news to cryto fans.
NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast.
National Blend of Models (NBM) Grib2 Format.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We have technology of Filecoin-Lotus.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://noaa-nbm-grib2-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02169597 GD
f01927410 US
f02234029 HK
f01955028 ZJ
f01106276 HB
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Voshell7** [comment]
@cryptoAmandaL Hi Amanda, can you approve my application?

**Comment by cryptoAmandaL** [comment]
@Voshell7 

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, and how you executed that plan)?

Do you agree to use the DataCap to only store data that abides by local regulations and is in compliance with the recipient miner’s terms of service?

Do you intend to store your data in a single geography or many?

Please DM me to confirm your identity.

**Comment by Voshell7** [comment]
@cryptoAmandaL 
Hi Amanda, I haven't received datacap previously.
Yes. We only store legal data. This dataset we want to store is a public search dataset on aws.
We will store data in more than 2 regions.
I gave you a slack dm just now. Thanks for your patience.

**Comment by cryptoAmandaL** [comment]
@Voshell7 Ok. Glad to support you. Please take seriously and insist on supporting the retrieval.

**Comment by Voshell7** [comment]
@cryptoAmandaL Hello Allocator, due to some technical reasons, we have stopped working with the original sp that we had been in contact with. We want to update the list of our sps.
f03100001 GD
f03100002 GD
f03099903 HK
f03088052 GD
f03098989 HK
f03100000 GD

**Comment by cryptoAmandaL** [comment]
@Voshell7 OK. Please continue to keep me informed of your changes. Please let these sps you're working with now to support retrieval.

**Comment by Voshell7** [comment]
@cryptoAmandaL Yes, they've already started updating their retrieval program.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by Voshell7** [comment]
@cryptoAmandaL Yes we do. Can allocator give us another round of datacap?

**Comment by cryptoAmandaL** [comment]
@Voshell7 It looks like the data in the report has stopped at the end of August. Do you have new sps' plan about your storage? The sps in your original plan showed too low retrieval results. It can not be allowed in my allocator rules.

**Comment by Voshell7** [comment]
@cryptoAmandaL OK. We are looking for good sps in last two months. We were trying to improve on what we had. Please give us a chance.

**Comment by Voshell7** [comment]
@cryptoAmandaL 
We have contacted these sps.
f01660795 GD
f03156722 US
f03216485 SC
f03066836 HN
f02816097 HK

**Comment by cryptoAmandaL** [comment]
Good! These sps' retrieval results are great. If you work with these sps the next step, your report will have a good grade.
![image](https://github.com/user-attachments/assets/92e8739e-43b7-4871-be86-e7cf5e8569a8)

**Comment by cryptoAmandaL** [comment]
@Voshell7 If you want to continue your storage plan, I suggest you submit a new application. But you should stop cooperating with sps in your previous report. They are unsatisfactory.

**Comment by Voshell7** [comment]
@cryptoAmandaL Yes we want to continue our storage plan. We can reapply an application and we have decided to work with new sps. Can we do it now?

**Comment by cryptoAmandaL** [comment]
@Voshell7 ok. I can give you the chance to improve your storage process.

**Comment by Voshell7** [comment]
@cryptoAmandaL We have already submitted a new application.
https://github.com/cryptoAmandaL/BDE-Allocator/issues/28

**Comment by cryptoAmandaL** [comment]
Close this application as a history.
