### ISSUE TITLE
[DataCap Application] Coupled Model IP 6

### ISSUE THREAD

**Issue by sarahfif** [cryptoAmandaL/BDE-Allocator#22]
### Version

1

### DataCap Applicant

sarahfif

### Project ID

1

### Data Owner Name

ESGF and Pangeo

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://wcrp-cmip.org/cmip6/

### Social Media Handle

sarah

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1792TiB

### Number of replicas to store

7

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1whjtbym63vnovx6itndqkj6k57jdzl5umaiuoly

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are an organization which has technology to store data and prepare data. We'd like to make data stored safely.
CMIP is a project of the World Climate Research Programme (WCRP) providing climate projections to understand past, present and future climate changes. CMIP and its associated data infrastructure have become essential to the Intergovernmental Panel on Climate Change (IPCC) and other international and national climate assessments.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Lotus is the best way to prepare data. We usually made data into car files by lotus. If clients want to choose another way to do it, we can use other program to pack data.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://cmip6-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02169597 Shenzhen
f02365890 Hongkong
f0509981 Guizhou
f01844118 Newyork
f02834511 Hongkong
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by sarahfif** [comment]
@cryptoAmandaL Hello notary, I'm Sarah, please check my application. If you have any questions about our application, please ping me at slack. Thank you so much.

**Comment by sarahfif** [comment]
![image](https://github.com/user-attachments/assets/2f125b73-c161-40ba-879d-43b6b40f1e6a)
I have left you the message on slack. Thank you.

**Comment by sarahfif** [comment]
![image](https://github.com/user-attachments/assets/798ec62c-02ee-4073-869d-dc280adcc152)
I have left you the message on slack. Thank you.

**Comment by cryptoAmandaL** [comment]
@sarahfif According to your application, please answer some questions. 

- Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, and how you executed that plan)?

- Do you agree to use the DataCap to only store data that abides by local regulations and is in compliance with the recipient miner’s terms of service?

- Do you intend to store your data in a single geography or many?

- Please DM me to confirm your identity.

**Comment by sarahfif** [comment]
@cryptoAmandaL 
Hello notary, I didn't receive datacap previously.
Yes, we agree to do that. We choose public dataset from aws. It is a good and academic dataset.
We will do our best to find SPs in different locations to store our data. Not a single geography.
![image](https://github.com/user-attachments/assets/0353ef6c-431f-4f07-8194-f1ebac8047dc)
I've replied to you. Thank you.

**Comment by cryptoAmandaL** [comment]
@sarahfif Got it. Remember one point that you should give me the latest sp list from time to time. This can make it easier for you to get further support.

**Comment by sarahfif** [comment]
@cryptoAmandaL OK. I know that. Thank you. Please approve my application.

**Comment by cryptoAmandaL** [comment]
Give you this chance.

**Comment by sarahfif** [comment]
@cryptoAmandaL We find some new SPs to cooperate, here's the sp list.
f03099988 HongKong
f01084941 HongKong
f03100001 Shenzhen
f02046115 USA
f03030649 China
f03156722 HongKong
f03100003 Shenzhen

**Comment by cryptoAmandaL** [comment]
checker:manualTrigger

**Comment by cryptoAmandaL** [comment]
The retrieval success rate looks as if it needs to be improved and hopefully something will be done about it.

**Comment by sarahfif** [comment]
@cryptoAmandaL Hello notary, I've talked with these sps yesterday afternoon. There were some network problems that led to these results. They are already dealing with these matters in a positive way. They promised that the scores will be much improved in the next round. Please look forward to the following reports.

**Comment by cryptoAmandaL** [comment]
If we don't see improvement in the next tranche, this may be your last chance.

**Comment by cryptoAmandaL** [comment]
checker:manualTrigger

**Comment by cryptoAmandaL** [comment]
See that the  retrieval success rate of Checker Report is improving, please keep up the good work!

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by sarahfif** [comment]
@cryptoAmandaL Hello allocator, can we open a new application based on this one? We would like to correct the sp retrieval data and remove sp's that are no longer cooperating from our retrieval reports.

**Comment by sarahfif** [comment]
@cryptoAmandaL Yes. Our original storage plan is not finished. But old sps' record seems exist in our report all the time. We've made the decision not to work with sps that don't support retrieval. We want to submit a new application to restart our storage plan. Also we will change into a new address to receive datacap. Can we?

**Comment by cryptoAmandaL** [comment]
@sarahfif ok. I think it is workable. Welcome.

**Comment by cryptoAmandaL** [comment]
Close this application as a history.
