### ISSUE TITLE
[DataCap Application] Community Earth System Model v2 ARISE

### ISSUE THREAD

**Issue by Mario8152** [cryptoAmandaL/BDE-Allocator#3]
### Version

1

### DataCap Applicant

Mario8152

### Project ID

/

### Data Owner Name

NCAR

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.ucar.edu/terms-of-use/data

### Social Media Handle

Mario

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

598TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1oogg7a2fixagwwnzl4s6wgsl4plkvppdy55ol6a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
UCAR is a hub for the Earth system sciences and a gateway to cutting-edge resources and services. Our team help save this dataset and choose filecoin as a safe way.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
ARISE-SAI-1.5 simulations include extensive output for the atmospheric, land, ocean and sea-ice model components. All model output for the simulations is in NetCDF format. All variables are in time-series format, with one variable per file. 3-dimensional atmospheric output is on the original 70 model levels. Output consists of standard monthly mean CMIP6 output for the atmospheric, land, ocean, and sea-ice models. In addition, higher-frequency (daily averaged, 3-hourly averaged, 3-hourly instantaneous, and 1-hourly mean) output is available for the atmospheric model. A listing of all output variables is available (output follows member 006 - 010 of the reference simulations described below).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We've downloaded this dataset into our storage servers. Then we would provide download links to sps.
```

### Please share a sample of the data

```text
s3://ncar-cesm2-arise/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How did you find your storage providers

Slack, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f01841134 China/f02029743 Singapore/f0420161 Canada/f02239446 HK/f01844118 US
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Mario8152** [comment]
Dear @cryptoAmandaL allocator, please check my application and give us a feedback. We need your help. Thank you.

**Comment by cryptoAmandaL** [comment]
@Mario8152 Is this your first and the only one application? Do you need more time for preparing all steps?

**Comment by Mario8152** [comment]
@cryptoAmandaL 
Yes. This is the first application and our first time for storing dataset in filecoin. 
No, we are ready for everything. We can start working now.

**Comment by Mario8152** [comment]
@cryptoAmandaL Thank you allocator!

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
SPs listed
f01841134 China/
f02029743 Singapore/
f0420161 Canada/
f02239446 HK/
f01844118 US

**Comment by Mario8152** [comment]
@filecoin-watchdog Hello sir, i have given the update of sps to allocator.

**Comment by galen-mcandrew** [comment]
checker:manualTrigger

**Comment by cryptoAmandaL** [comment]
![image](https://github.com/cryptoAmandaL/BDE-Allocator/assets/134273610/0cf92da0-fb32-43ff-a9ae-b4e2bef6c51b)

**Comment by cryptoAmandaL** [comment]
Too many bugs to work. Hope to fix it soon.

**Comment by cryptoAmandaL** [comment]
@Mario8152 There's some bug in allocator.tech so that I can not continue allocate datacap any more.
I will close this application. If you need more datacap, please reapply to me.
