### ISSUE TITLE
[DataCap Application] ENCODE AWS PUBLIC DATASET

### ISSUE THREAD

**Issue by huGenet21** [cryptoAmandaL/BDE-Allocator#8]
### Version

1

### DataCap Applicant

Genet

### Project ID

1

### Data Owner Name

NHGRI

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org

### Social Media Handle

Genet

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1.2PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1ndoet7zzentwwqqcge4rrnnurkjvz3qmc23miqq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The ENCODE Consortium not only produces high-quality data, but also analyzes the data in an integrative fashion. The ENCODE Encyclopedia organizes the most salient analysis products into annotations and provides tools to search and visualize them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Encyclopedia of DNA Elements (ENCODE) Consortium is an international collaboration of research groups funded by the National Human Genome Research Institute (NHGRI). The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active. ENCODE investigators employ a variety of assays and methods to identify functional elements. The discovery and annotation of gene elements is accomplished primarily by sequencing a diverse range of RNA sources, comparative genomics, integrative bioinformatic methods, and human curation. Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I downloaded this dataset and make it into car files by Lotus.
We support sp receiving these car files online.
```

### Please share a sample of the data

```text
s3://encode-public/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Big Data Exchange

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f0132178, Hangzhou
2. f01084913, HongKong
3. f02363999, Singapore
4. f01788231, US
5. f01844043, US
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by huGenet21** [comment]
Dear allocator, we are ready for storage. Can you please check our application and give us some feedback?

**Comment by cryptoAmandaL** [comment]
Hello @huGenet21 

- Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, and how you executed that plan)?

- Do you agree to use the DataCap to only store data that abides by local regulations and is in compliance with the recipient miner’s terms of service?

- Do you intend to store your data in a single geography or many?

- Please DM me to confirm your identity.

**Comment by huGenet21** [comment]
Dear allocator, @cryptoAmandaL 

We have not applied for datacap in the past.
Sure, we agree to store useful data that abides by local regulations and is in compliance with the recipient miner’s terms of service.
We intend to store data in many geography. We have contacted with some sps in different regions.
I dm you in slack. My handle name is Genet.

**Comment by cryptoAmandaL** [comment]
@huGenet21 ok, I have got your slack message, I'll support you the first round and give you a try. Please take seriously.

**Comment by huGenet21** [comment]
Thank you allocator

**Comment by galen-mcandrew** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by cryptoAmandaL** [comment]
checker:manualTrigger

**Comment by cryptoAmandaL** [comment]
From the result of bot-report, we can only allocate the last tranche,up to 512Tib, and if we don't see a significant change, we will stop allocating. Of course, we'd like to see your efforts.

**Comment by huGenet21** [comment]
checker:manualTrigger

**Comment by huGenet21** [comment]
@cryptoAmandaL Dear allocator, thank you for your trust. Still the sps we are partnering with haven't been able to solve the problem of low retrieval success rate, and they are still in constant communication with the spark team. Please give us some more time to prepare. Thank you!

**Comment by cryptoAmandaL** [comment]
@huGenet21 It seems that the retrieval success rate has not improved and we have decided to end our work with you.
